# Generated by Django 3.0.1 on 2019-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maker',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='maker',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='word',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
