# Generated by Django 3.0.1 on 2019-12-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191224_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='times_appeared',
            field=models.IntegerField(default=0),
        ),
    ]
