# Generated by Django 3.0.1 on 2019-12-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_word_times_appeared'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
