# Generated by Django 3.0.1 on 2019-12-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_category_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_categories', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='selected',
        ),
        migrations.AlterField(
            model_name='word',
            name='word_text',
            field=models.CharField(max_length=30),
        ),
    ]
