# Generated by Django 3.0.1 on 2019-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20191228_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='axk9', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='team_name_one',
            field=models.CharField(default='Bionic Beaver', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='team_name_two',
            field=models.CharField(default='Buster', max_length=20),
        ),
    ]
