# Generated by Django 3.0.1 on 2019-12-29 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20191229_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='3mgq', max_length=20),
        ),
    ]
